language: ruby
rvm:
  - 2.5.1

branches:
  only:
    - master

cache:
  bundler:
  directories:
    - /home/travis/tmp/
    - /home/travis/.rvm/

services:
  - postgresql
  - docker

before_install:
  - if [ ! -d /home/travis/tmp ]; then mkdir /home/travis/tmp; fi
  - gem install bundler
  - cd server

install: bundle install --jobs=3 --retry=3

before_script:
  - bundle exec rails db:reset

script:
  - bundle exec rspec

after_success:
  - cd ..
  - if [ -f /home/travis/tmp/images.tar.gz ]; then gzip -dc /home/travis/tmp/images.tar.gz | docker load; fi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.cn-shenzhen.aliyuncs.com
  - docker build -t registry.cn-shenzhen.aliyuncs.com/open_flutter/open_flutter:latest .
  - docker push registry.cn-shenzhen.aliyuncs.com/open_flutter/open_flutter:latest
  - docker save registry.cn-shenzhen.aliyuncs.com/open_flutter/open_flutter:latest | gzip > /home/travis/tmp/images.tar.gz

addons:
  postgresql: "9.6"
